% run the KinTrans st-gcn experiments

ProcessHMKinTrans_1_NN_DTW;
ProcessHMKinTrans_1_NN_DFD;
ProcessHMKinTrans_1_NN_CFD;
ProcessHMKinTrans_1_NN_ED;
ProcessHMKinTrans_1_SD_DTW;
ProcessHMKinTrans_1_SD_DFD;
% ProcessHMKinTrans_1_SD_CFD;
ProcessHMKinTrans_1_SD_ED;

ProcessHMKinTrans_5pct_NN_DTW;
ProcessHMKinTrans_5pct_NN_DFD;
ProcessHMKinTrans_5pct_NN_CFD;
ProcessHMKinTrans_5pct_NN_ED;
ProcessHMKinTrans_5pct_SD_DTW;
ProcessHMKinTrans_5pct_SD_DFD;
% ProcessHMKinTrans_5pct_SD_CFD;
ProcessHMKinTrans_5pct_SD_ED;

ProcessHMKinTrans_10pct_NN_DTW;
ProcessHMKinTrans_10pct_NN_DFD;
ProcessHMKinTrans_10pct_NN_CFD;
ProcessHMKinTrans_10pct_NN_ED;
ProcessHMKinTrans_10pct_SD_DTW;
ProcessHMKinTrans_10pct_SD_DFD;
% ProcessHMKinTrans_10pct_SD_CFD;
ProcessHMKinTrans_10pct_SD_ED;

ProcessHMKinTrans_20pct_NN_DTW;
ProcessHMKinTrans_20pct_NN_DFD;
ProcessHMKinTrans_20pct_NN_CFD;
ProcessHMKinTrans_20pct_NN_ED;
ProcessHMKinTrans_20pct_SD_DTW;
ProcessHMKinTrans_20pct_SD_DFD;
% ProcessHMKinTrans_20pct_SD_CFD;
ProcessHMKinTrans_20pct_SD_ED;
